<?php
require_once __DIR__ . '/config.php';
require_admin_session();

$conn = get_db_connection();
$albumId = !empty($_GET['album_id']) ? (int) $_GET['album_id'] : null;
$dateFrom = $_GET['date_from'] ?? date('Y-m-01');
$dateTo = $_GET['date_to'] ?? date('Y-m-d');

if (!$albumId) {
    $_SESSION['admin_flash'] = 'No album selected.';
    header('Location: analytics.php');
    exit;
}

// Get album and client info
$stmt = $conn->prepare("SELECT a.client_names, a.slug, a.client_id, c.username FROM albums a LEFT JOIN clients c ON c.id = a.client_id WHERE a.id = ? LIMIT 1");
$stmt->bind_param('i', $albumId);
$stmt->execute();
$stmt->bind_result($clientNames, $slug, $clientId, $clientEmail);
if (!$stmt->fetch()) {
    $_SESSION['admin_flash'] = 'Album not found.';
    header('Location: analytics.php');
    exit;
}
$stmt->close();

// Get analytics stats
$stmt = $conn->prepare("SELECT COUNT(*) FROM analytics WHERE album_id = ? AND viewed_at BETWEEN ? AND ?");
$stmt->bind_param('iss', $albumId, $dateFrom, $dateTo);
$stmt->execute();
$stmt->bind_result($totalViews);
$stmt->fetch();
$stmt->close();

$stmt = $conn->prepare("SELECT COUNT(DISTINCT ip_address) FROM analytics WHERE album_id = ? AND viewed_at BETWEEN ? AND ?");
$stmt->bind_param('iss', $albumId, $dateFrom, $dateTo);
$stmt->execute();
$stmt->bind_result($uniqueVisitors);
$stmt->fetch();
$stmt->close();

// Get daily breakdown
$dailyViews = [];
$stmt = $conn->prepare("SELECT DATE(viewed_at) as date, COUNT(*) as views FROM analytics WHERE album_id = ? AND view_type = 'gallery' AND viewed_at BETWEEN ? AND ? GROUP BY DATE(viewed_at) ORDER BY date DESC");
$stmt->bind_param('iss', $albumId, $dateFrom, $dateTo);
$stmt->execute();
$stmt->bind_result($date, $views);
while ($stmt->fetch()) {
    $dailyViews[] = ['date' => $date, 'views' => $views];
}
$stmt->close();

// Generate email body
$emailBody = "Gallery Analytics Report\n";
$emailBody .= "========================\n\n";
$emailBody .= "Gallery: {$clientNames} ({$slug})\n";
$emailBody .= "Period: " . date('F j, Y', strtotime($dateFrom)) . " - " . date('F j, Y', strtotime($dateTo)) . "\n\n";
$emailBody .= "Summary\n";
$emailBody .= "-------\n";
$emailBody .= "Total Views: " . number_format($totalViews) . "\n";
$emailBody .= "Unique Visitors: " . number_format($uniqueVisitors) . "\n\n";

if (!empty($dailyViews)) {
    $emailBody .= "Daily Breakdown\n";
    $emailBody .= "---------------\n";
    foreach ($dailyViews as $row) {
        $emailBody .= date('F j, Y', strtotime($row['date'])) . ": " . number_format($row['views']) . " views\n";
    }
}

$emailBody .= "\n\nThis report was generated by Your Wedding Gallery Analytics.\n";
$emailBody .= "Visit your gallery at: " . (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . '/gallery.php?slug=' . urlencode($slug) . "\n";

$subject = "Monthly Gallery Report: {$clientNames}";

// Try to send email if client has email
$sent = false;
$errorMessage = '';
if (!empty($clientEmail) && filter_var($clientEmail, FILTER_VALIDATE_EMAIL)) {
    global $config;
    $mailConfig = $config['mail'];
    if (!empty($mailConfig['host']) && !empty($mailConfig['username']) && !empty($mailConfig['password'])) {
        require_once '/home/lochstud/vendors/PHPMailer/src/Exception.php';
        require_once '/home/lochstud/vendors/PHPMailer/src/PHPMailer.php';
        require_once '/home/lochstud/vendors/PHPMailer/src/SMTP.php';
        $mail = new PHPMailer\PHPMailer\PHPMailer(true);
        try {
            // Server settings
            $mail->isSMTP();
            $mail->Host = $mailConfig['host'];
            $mail->SMTPAuth = true;
            $mail->Username = $mailConfig['username'];
            $mail->Password = $mailConfig['password'];
            $mail->SMTPSecure = PHPMailer\PHPMailer\PHPMailer::ENCRYPTION_STARTTLS;
            $mail->Port = 587;
            // Recipients
            $mail->setFrom($mailConfig['from_email'], $mailConfig['from_name']);
            $mail->addAddress($clientEmail, $clientNames);
            $mail->addReplyTo('support@lochstudios.com', 'LochStudios Support');
            // Content
            $mail->isHTML(false);
            $mail->Subject = $subject;
            $mail->Body = $emailBody;
            $mail->send();
            $sent = true;
        } catch (Exception $e) {
            $errorMessage = "Mailer Error: {$mail->ErrorInfo}";
        }
    } else {
        $errorMessage = "Mail configuration incomplete.";
    }
}

if ($sent) {
    $_SESSION['admin_flash'] = "Report sent successfully to {$clientEmail}";
} else {
    $_SESSION['admin_flash'] = "Could not send email. " . ($errorMessage ?: "Client email: " . ($clientEmail ?: 'not set')) . ". Report generated below.";
}
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Report Sent | Your Wedding</title>
        <link rel="icon" href="4803712.png" type="image/png" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="style.css?v=<?php echo uuidv4(); ?>" />
    </head>
    <body>
        <?php include_once __DIR__ . '/nav.php'; ?>
        <section class="section full-bleed full-height">
            <div class="container is-fluid">
                <h1 class="title">Analytics Report</h1>
                <?php if ($sent): ?>
                    <div class="notification is-success">
                        Report successfully sent to <?php echo htmlspecialchars($clientEmail); ?>
                    </div>
                <?php else: ?>
                    <div class="notification is-warning">
                        <?php echo htmlspecialchars($_SESSION['admin_flash'] ?? 'Unable to send email.'); ?>
                    </div>
                <?php endif; ?>
                <div class="box">
                    <h2 class="title is-5">Report Preview</h2>
                    <pre class="report-preview"><?php echo htmlspecialchars($emailBody); ?></pre>
                </div>
                <div class="buttons">
                    <a href="analytics.php?album_id=<?php echo $albumId; ?>&date_from=<?php echo urlencode($dateFrom); ?>&date_to=<?php echo urlencode($dateTo); ?>" class="button is-link">Back to Analytics</a>
                    <a href="dashboard.php" class="button is-light">Dashboard</a>
                </div>
            </div>
        </section>
    </body>
</html>
